In [14]:
import pandas as pd
import numpy as np

In [15]:

pd.DataFrame({'A': [1, 2, 3]})

   A
0  1
1  2
2  3

In [16]:
 a = 1
 a

1

In [17]:
s = pd.Series([1, 3, 5, 6, 8])
s

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [38]:
dates = pd.date_range("20260716", periods=6)

dates

DatetimeIndex(['2026-07-16', '2026-07-17', '2026-07-18', '2026-07-19',
               '2026-07-20', '2026-07-21'],
              dtype='datetime64[ns]', freq='D')

In [19]:

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

df

                   A         B         C         D
2013-01-01 -1.341932 -0.267894  0.735365  0.163906
2013-01-02  1.014039 -0.768250  0.286704  0.072906
2013-01-03 -0.584604  1.758341  0.071529  0.343721
2013-01-04 -1.812713  1.306117  0.933119  1.353094
2013-01-05  0.175526 -0.961227 -1.187927  0.388883
2013-01-06  0.075233 -1.042332 -0.162188 -0.598864

In [32]:

df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [33]:
a= np.random.randn(6,3)
a

array([[ 1.09755087, -0.05376283,  2.0439433 ],
       [-1.79243088,  0.21073049,  0.14891336],
       [ 1.07118019, -0.15731758,  0.15185287],
       [ 1.44488917,  1.66193221,  0.57494236],
       [ 1.67953907,  0.71948525, -0.35470682],
       [ 0.4340473 , -1.67415289, -0.73262779]])

In [34]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [36]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [37]:
df2.head()

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo